// <auto-generated />
namespace EnglishTestingOnline.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addshocvien : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addshocvien));
        
        string IMigrationMetadata.Id
        {
            get { return "201810090829118_add-s-hocvien"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
